### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by nicoruti** [atosconsulting/chopen_2016_labs#1]
Hi @thomashug and @bartoszmajsak 
Thanks again for the great workshop! Could you upload the presentation you held at Rapperswil?
Thanks

**Comment by thomashug** [comment]
Thanks for the note @nicoruti - we have to remove some licensed images until we're ready to go. @bartoszmajsak should we publish the HTML it as GitHub pages?

**Comment by bartoszmajsak** [comment]
I think that will be the easiest. +1 to gh-pages

**Comment by thomashug** [comment]
@bartoszmajsak would you mind removing your licensed graphics? I can try then to figure out how to get the HTML out of the Docker tooling chain :-)

**Comment by thomashug** [comment]
@bartoszmajsak tried to remove all your images. Pleaes fix otherwise :-)

@nicoruti slides are uploaded and accessible under https://atosconsulting.github.io/chopen_2016_labs/index.html - sorry the delay!

**Comment by bartoszmajsak** [comment]
Sorry, being on the road last few days. LGTM. Thanks for taking care of it!

**Comment by nicoruti** [comment]
Cool, thanks a lot!
